<?php

 $title = 'My Fournitures';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('fourniture', array('action'=>'add'));?>">Add new fourniture</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Quantity</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($commandes as $commande) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($fourniture->name);?></td>
     <td><?php echo $this->escapeHtml($fourniture->quantity);?></td>
     <td>
         <a href="<?php echo $this->url('fourniture',
             array('action'=>'edit', 'id' => $fourniture->id));?>">Edit</a>
         <a href="<?php echo $this->url('fourniture',
             array('action'=>'delete', 'id' => $fourniture->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>