<?php

$title = 'Add new product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('produit', array('action' => 'add')));
$form->setAttribute('class', 'form');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('prix'));
echo $this->formRow($form->get('id_restaurant'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();