<h1> Votre panier </h1>
<?php if(isset($error)){ echo $error; } ?>
<?php if(isset($_SESSION['user']['panier'])) { ?>
<a href="<?php echo $this->url('produit', array('action' => 'cleanPanier')); ?>"><h3 style="float:right;"> Vider votre panier </h3></a>
<?php } ?>

<?php
if(isset($_SESSION['user']['panier']))
{
	foreach($produits as $key => $produit)
		{
			echo $produit->name . '<a href="'.$this->url('produit', array('action' => 'removeItem', 'id' => $key)).'">'  . "<input type='button' value='-' /></a>" . "<br>";
			echo $produit->prix . "<br> <hr />";
		}
}
 ?>
<?php if(isset($_SESSION['user']['panier'])) { ?>
 <h4> Total a payer : <?php echo $total . '€'; ?></h4>
 <?php } ?>
 <a href="<?php echo $this->url('restaurant', array('action' => 'carte', 'id' => $id_resto)); ?>"> Continuer mes achats ! </a>
 <?php if(isset($total) && !$total == '0') { ?><a style="float:right;" href="<?php echo $this->url('commande', array('action' => 'commander')) ?>"> <input type="button" value="Commander"/> </a> <?php } ?>