 <?php

 $title = 'Edit restaurant';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'restaurant',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('adresse'));
echo $this->formRow($form->get('tel'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();