<?php

 $title = 'Restaurants';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php if(isset($_SESSION['user'])) { 
    if(isset($_SESSION['user']['role'])) { 
        if($_SESSION['user']['role'] == '3') { ?>
 <p>
     <a href="<?php echo $this->url('restaurant', array('action'=>'add'));?>">Add a new restaurant</a>
 </p> <?php } } } ?>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Adresse</th>
     <th>Telephone</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($restaurants as $restaurant) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($restaurant->name);?></td>
     <td><?php echo $this->escapeHtml($restaurant->adresse);?></td>
     <td><?php echo $this->escapeHtml($restaurant->tel); ?></td>
     <td>
        <?php if(isset($_SESSION['user'])) { 
            if(isset($_SESSION['user']['role'])) { 
                if($_SESSION['user']['role'] == '3') { ?>
         <a href="<?php echo $this->url('restaurant',
             array('action'=>'edit', 'id' => $restaurant->id));?>">Edit</a>
         <a href="<?php echo $this->url('restaurant',
             array('action'=>'delete', 'id' => $restaurant->id));?>">Delete</a>
        <?php } } } ?>
     </td>
     <td> <a href="<?php echo $this->url('restaurant',
         array('action' => 'carte', 'id' => $restaurant->id)); ?>"><input type="submit" value="Choisir"/></a> 
    </td>
 </tr>
 <?php endforeach; ?>
 </table>