<?php 
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
 
if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}

?>
 
 <?php echo $this->translate('Pas encore inscrit?'); ?> <a href="<?php echo $this->url('user',array('action' => 'register')) ?>"><?php echo $this->translate('Register!'); ?></a>