<?php echo $this->doctype(); ?>
<?php 
use Zend\Session\Container;
$session = new Container('user'); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if(isset($_SESSION['user'])) {
                                if(isset($_SESSION['user']['role'])) {
                                    if($_SESSION['user']['role'] == '3') { ?>
                        <li class="active">
                            <a href="<?php echo $this->url('user', array('action' => 'index')) ?>"><?php echo $this->translate('Users') ?></a>
                        </li>
                        <?php } } } ?>
                        <?php 
                        if(isset($_SESSION['user'])) { 
                            if(isset($_SESSION['user']['role'])) { 
                                if($_SESSION['user']['role'] == '3') { ?>
                        <li class="active">
                            <a href="<?php echo $this->url('fourniture') ?>"><?php echo $this->translate('Fournitures') ?> </a>
                        </li>
                        <?php } } } ?>
                        <?php if(isset($_SESSION['user'])) {
                                if(isset($_SESSION['user']['role'])) {
                                    if($_SESSION['user']['role'] == '3') { ?>
                        <li class="active">
                            <a href="<?php echo $this->url('produit') ?>"><?php echo $this->translate('Produits ') ?> </a>
                        </li>
                        <?php } } } ?>
                        <li class="active">
                            <a href="<?php echo $this->url('restaurant') ?>"><?php echo $this->translate('Nos restaurants') ?> </a>
                        </li>
                        <?php if(!isset($_SESSION['user']['username'])) { ?>
                        <li class="active">
                            <a href="<?php echo $this->url('user', array('action' => 'register')) ?>"><?php echo $this->translate('Register') ?></a>
                        </li>
                        <?php } ?>
                        <?php if(isset($_SESSION['user']) && !empty($_SESSION['user']['username'])) { ?> 
                        <li>
                            <a href="<?php echo $this->url('user', array('action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a>
                        </li>
                        <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
